### ISSUE TITLE
installing PEcAnRTM

### ISSUE THREAD

**Issue by annakat** [ashiklom/PEcAnRTM#1]
Dear Alexey, I'm having trouble installing PEcAnRTM. I'm using macOS Catalina 10.15.7. and R 4.0.3. Looking at the error message it looks like the fortran issue mentioned in the readme. I tried adding the Makevars.txt and also checked the Makeconf file, but can't figure it out. Any ideas? Best greetings, Anna

![Screen Shot 2020-12-02 at 1 11 59 PM](https://user-images.githubusercontent.com/12850473/100872626-5d530400-34a2-11eb-9c3f-c8721911aa30.png)
![Screen Shot 2020-12-02 at 1 11 49 PM](https://user-images.githubusercontent.com/12850473/100872633-617f2180-34a2-11eb-908a-a75dd2c911aa.png)

##########
devtools::install_github("ashiklom/pecanrtm")
Downloading GitHub repo ashiklom/pecanrtm@HEAD
✓  checking for file ‘/private/var/folders/rz/v02695116ts4xp1l4m9_ntwc0000gr/T/RtmpH3rzwh/remotes715764f8be4/ashiklom-PEcAnRTM-e4ac0d6/DESCRIPTION’ ...
─  preparing ‘PEcAnRTM’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘PEcAnRTM_1.7.1.tar.gz’
   
* installing *source* package ‘PEcAnRTM’ ...
** using staged installation
** libs
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c  RTM/modules/mod_types.f90 -o RTM/modules/mod_types.o
make: gfortran: No such file or directory
make: *** [RTM/modules/mod_types.o] Error 1
ERROR: compilation failed for package ‘PEcAnRTM’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/PEcAnRTM’
Error: Failed to install 'PEcAnRTM' from GitHub:
  (converted from warning) installation of package ‘/var/folders/rz/v02695116ts4xp1l4m9_ntwc0000gr/T//RtmpH3rzwh/file7156069626a/PEcAnRTM_1.7.1.tar.gz’ had non-zero exit status

**Comment by ashiklom** [comment]
Hi Anna -- Thanks for the report, and sorry the install isn't working! Compiling this package has always been a pain on Windows.

If you're just looking to do some PROSPECT and/or SAIL simulations, I would suggest giving my `rrtm` package a shot: https://github.com/ashiklom/rrtm. The goal there was to keep things pure R as much as possible, so it should be much easier to install, and the performance ends up being pretty similar. At some point, I'm planning on phasing out the Fortran from this package in favor of plain R.

**Comment by annakat** [comment]
Install worked for R-4.2.2-arm64, Apple Silicon Mac M1, Ventura 13.2.1
First, install Fortan compiler from here: https://mac.r-project.org/tools/ 
Make sure use terminal to unpack tar ball and to run gfortran-update-sdk (as described above) 
```
install.packages('PEcAnRTM', repos = c('https://pecanproject.r-universe.dev',
                                       'https://cloud.r-project.org'))
```
